"""Add patient features tables

Revision ID: 80aaaf79fcf0
Revises: f7dcf55ada63
Create Date: 2026-08-28 23:14:05.714718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80aaaf79fcf0'
down_revision: Union[str, Sequence[str], None] = 'f7dcf55ada63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_categories_name'), 'activity_categories', ['name'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['activity_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_category_id'), 'activities', ['category_id'], unique=False)
    op.create_table('daily_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('scheduled_time', sa.String(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('recurrence_rule', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_patient_date', 'daily_tasks', ['patient_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_tasks_date'), 'daily_tasks', ['date'], unique=False)
    op.create_index(op.f('ix_daily_tasks_patient_id'), 'daily_tasks', ['patient_id'], unique=False)
    op.create_index(op.f('ix_daily_tasks_task_type'), 'daily_tasks', ['task_type'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('recurrence_rule', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminders_patient_active', 'reminders', ['patient_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_reminders_patient_id'), 'reminders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_reminders_scheduled_at'), 'reminders', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_reminders_type'), 'reminders', ['type'], unique=False)
    op.create_table('activity_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_sessions_activity_id'), 'activity_sessions', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_sessions_patient_id'), 'activity_sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_activity_sessions_started_at'), 'activity_sessions', ['started_at'], unique=False)
    op.create_table('activity_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('mistakes', sa.Integer(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['activity_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_results_created_at'), 'activity_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_results_session_id'), 'activity_results', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_results_session_id'), table_name='activity_results')
    op.drop_index(op.f('ix_activity_results_created_at'), table_name='activity_results')
    op.drop_table('activity_results')
    op.drop_index(op.f('ix_activity_sessions_started_at'), table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_patient_id'), table_name='activity_sessions')
    op.drop_index(op.f('ix_activity_sessions_activity_id'), table_name='activity_sessions')
    op.drop_table('activity_sessions')
    op.drop_index(op.f('ix_reminders_type'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_scheduled_at'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_patient_id'), table_name='reminders')
    op.drop_index('idx_reminders_patient_active', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_daily_tasks_task_type'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_patient_id'), table_name='daily_tasks')
    op.drop_index(op.f('ix_daily_tasks_date'), table_name='daily_tasks')
    op.drop_index('idx_tasks_patient_date', table_name='daily_tasks')
    op.drop_table('daily_tasks')
    op.drop_index(op.f('ix_activities_category_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_activity_categories_name'), table_name='activity_categories')
    op.drop_table('activity_categories')
    # ### end Alembic commands ###
