"""add_caregiver_dashboard_and_mood_alerts

Revision ID: cc8236e206af
Revises: 80aaaf79fcf0
Create Date: 2026-08-29 12:58:44.119766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8236e206af'
down_revision: Union[str, Sequence[str], None] = '80aaaf79fcf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_patient_unread', 'patient_alerts', ['patient_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_patient_alerts_alert_type'), 'patient_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_patient_alerts_created_at'), 'patient_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_alerts_patient_id'), 'patient_alerts', ['patient_id'], unique=False)
    op.create_table('patient_moods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('recorded_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_moods_patient_date', 'patient_moods', ['patient_id', 'recorded_date'], unique=False)
    op.create_index(op.f('ix_patient_moods_patient_id'), 'patient_moods', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_moods_recorded_date'), 'patient_moods', ['recorded_date'], unique=False)
    op.add_column('connection_codes', sa.Column('patient_id', sa.String(length=36), nullable=False))
    op.drop_constraint(op.f('connection_codes_caregiver_id_fkey'), 'connection_codes', type_='foreignkey')
    op.create_foreign_key(None, 'connection_codes', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_column('connection_codes', 'caregiver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection_codes', sa.Column('caregiver_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'connection_codes', type_='foreignkey')
    op.create_foreign_key(op.f('connection_codes_caregiver_id_fkey'), 'connection_codes', 'users', ['caregiver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('connection_codes', 'patient_id')
    op.drop_index(op.f('ix_patient_moods_recorded_date'), table_name='patient_moods')
    op.drop_index(op.f('ix_patient_moods_patient_id'), table_name='patient_moods')
    op.drop_index('idx_moods_patient_date', table_name='patient_moods')
    op.drop_table('patient_moods')
    op.drop_index(op.f('ix_patient_alerts_patient_id'), table_name='patient_alerts')
    op.drop_index(op.f('ix_patient_alerts_created_at'), table_name='patient_alerts')
    op.drop_index(op.f('ix_patient_alerts_alert_type'), table_name='patient_alerts')
    op.drop_index('idx_alerts_patient_unread', table_name='patient_alerts')
    op.drop_table('patient_alerts')
    # ### end Alembic commands ###
